# Generated by Django 4.2.16 on 2025-07-30 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Factura')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión')),
                ('due_date', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('payment_terms', models.CharField(choices=[('immediate', 'Inmediato'), ('15_days', '15 días'), ('30_days', '30 días'), ('60_days', '60 días'), ('90_days', '90 días')], default='30_days', max_length=20, verbose_name='Términos de Pago')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviada'), ('paid', 'Pagada'), ('overdue', 'Vencida'), ('cancelled', 'Cancelada')], default='draft', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Impuestos')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Descuento')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('terms_conditions', models.TextField(blank=True, verbose_name='Términos y Condiciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment', verbose_name='Cita')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Servicio')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa de Impuesto (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Categoría')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Pago')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta de Crédito/Débito'), ('transfer', 'Transferencia Bancaria'), ('check', 'Cheque'), ('insurance', 'Seguro Médico'), ('other', 'Otro')], max_length=20, verbose_name='Método de Pago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Estado')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Número de Referencia')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('check_number', models.CharField(blank=True, max_length=50, verbose_name='Número de Cheque')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice', verbose_name='Factura')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Procesado por')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=8, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa de Impuesto (%)')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Descuento (%)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice', verbose_name='Factura')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Elemento de Factura',
                'verbose_name_plural': 'Elementos de Factura',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Reclamo')),
                ('insurance_company', models.CharField(max_length=200, verbose_name='Compañía de Seguros')),
                ('policy_number', models.CharField(max_length=100, verbose_name='Número de Póliza')),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del Reclamo')),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Aprobado')),
                ('submission_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('response_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Respuesta')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Enviado'), ('under_review', 'En Revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('paid', 'Pagado')], default='draft', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Razón de Rechazo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_claims', to='billing.invoice', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Reclamo de Seguro',
                'verbose_name_plural': 'Reclamos de Seguros',
                'ordering': ['-created_at'],
            },
        ),
    ]
