# Generated by Django 4.2.16 on 2025-08-04 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecordTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Plantilla')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('category', models.CharField(choices=[('general', 'General'), ('pediatria', 'Pediatría'), ('ginecologia', 'Ginecología'), ('cardiologia', 'Cardiología'), ('neurologia', 'Neurología'), ('dermatologia', 'Dermatología'), ('traumatologia', 'Traumatología'), ('psiquiatria', 'Psiquiatría'), ('oftalmologia', 'Oftalmología'), ('otorrinolaringologia', 'Otorrinolaringología'), ('otra', 'Otra')], default='general', max_length=100, verbose_name='Categoría')),
                ('fields_config', models.JSONField(default=dict, help_text='JSON con la configuración de campos incluidos', verbose_name='Configuración de Campos')),
                ('include_basic_info', models.BooleanField(default=True, verbose_name='Incluir Información Básica')),
                ('include_vital_signs', models.BooleanField(default=True, verbose_name='Incluir Signos Vitales')),
                ('include_allergies', models.BooleanField(default=True, verbose_name='Incluir Alergias')),
                ('include_medications', models.BooleanField(default=True, verbose_name='Incluir Medicamentos')),
                ('include_family_history', models.BooleanField(default=True, verbose_name='Incluir Historial Familiar')),
                ('include_social_history', models.BooleanField(default=True, verbose_name='Incluir Historial Social')),
                ('include_emergency_contact', models.BooleanField(default=True, verbose_name='Incluir Contacto de Emergencia')),
                ('custom_fields', models.JSONField(default=list, help_text='Lista de campos personalizados adicionales', verbose_name='Campos Personalizados')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('is_public', models.BooleanField(default=False, help_text='Disponible para todas las organizaciones', verbose_name='Pública')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Veces Utilizada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_templates', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Plantilla de Expediente',
                'verbose_name_plural': 'Plantillas de Expedientes',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
