# Generated by Django 4.2.16 on 2025-07-30 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Equipo')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Número de Serie')),
                ('asset_tag', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Etiqueta de Activo')),
                ('status', models.CharField(choices=[('operational', 'Operativo'), ('maintenance', 'En Mantenimiento'), ('repair', 'En Reparación'), ('out_of_service', 'Fuera de Servicio'), ('retired', 'Retirado')], default='operational', max_length=20, verbose_name='Estado')),
                ('condition', models.CharField(choices=[('excellent', 'Excelente'), ('good', 'Bueno'), ('fair', 'Regular'), ('poor', 'Malo'), ('critical', 'Crítico')], default='good', max_length=20, verbose_name='Condición')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio de Compra')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Compra')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='Vencimiento de Garantía')),
                ('specifications', models.JSONField(blank=True, default=dict, verbose_name='Especificaciones Técnicas')),
                ('manual_url', models.URLField(blank=True, verbose_name='URL del Manual')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Último Mantenimiento')),
                ('next_maintenance', models.DateField(blank=True, null=True, verbose_name='Próximo Mantenimiento')),
                ('maintenance_frequency_days', models.PositiveIntegerField(default=90, verbose_name='Frecuencia de Mantenimiento (días)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Categoría de Equipo',
                'verbose_name_plural': 'Categorías de Equipos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('floor', models.CharField(blank=True, max_length=50, verbose_name='Piso')),
                ('room_number', models.CharField(blank=True, max_length=50, verbose_name='Número de Habitación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Persona de Contacto')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Preventivo'), ('corrective', 'Correctivo'), ('emergency', 'Emergencia'), ('calibration', 'Calibración'), ('inspection', 'Inspección')], max_length=20, verbose_name='Tipo de Mantenimiento')),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('cancelled', 'Cancelado'), ('postponed', 'Pospuesto')], default='scheduled', max_length=20, verbose_name='Estado')),
                ('scheduled_date', models.DateField(verbose_name='Fecha Programada')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('description', models.TextField(verbose_name='Descripción del Trabajo')),
                ('work_performed', models.TextField(blank=True, verbose_name='Trabajo Realizado')),
                ('parts_replaced', models.TextField(blank=True, verbose_name='Partes Reemplazadas')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo de Mano de Obra')),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo de Partes')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Total')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Próximo Mantenimiento Recomendado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='equipment.equipment', verbose_name='Equipo')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_maintenance', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_work', to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Registro de Mantenimiento',
                'verbose_name_plural': 'Registros de Mantenimiento',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Inicio de Uso')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fin de Uso')),
                ('purpose', models.CharField(max_length=200, verbose_name='Propósito del Uso')),
                ('patient_name', models.CharField(blank=True, max_length=200, verbose_name='Paciente (si aplica)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='equipment.equipment', verbose_name='Equipo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Uso',
                'verbose_name_plural': 'Registros de Uso',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('maintenance_due', 'Mantenimiento Vencido'), ('calibration_due', 'Calibración Vencida'), ('warranty_expiring', 'Garantía por Vencer'), ('malfunction', 'Mal Funcionamiento'), ('out_of_service', 'Fuera de Servicio'), ('custom', 'Personalizada')], max_length=20, verbose_name='Tipo de Alerta')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='Prioridad')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resuelta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='equipment.equipment', verbose_name='Equipo')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por')),
            ],
            options={
                'verbose_name': 'Alerta de Equipo',
                'verbose_name_plural': 'Alertas de Equipos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmentcategory', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.location', verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.supplier', verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='CalibrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='Fecha Programada')),
                ('performed_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Realización')),
                ('next_calibration_date', models.DateField(blank=True, null=True, verbose_name='Próxima Calibración')),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('completed', 'Completada'), ('failed', 'Fallida'), ('cancelled', 'Cancelada')], default='scheduled', max_length=20, verbose_name='Estado')),
                ('passed', models.BooleanField(blank=True, null=True, verbose_name='Pasó la Calibración')),
                ('calibration_standards', models.TextField(blank=True, verbose_name='Estándares de Calibración')),
                ('measurements_before', models.JSONField(blank=True, default=dict, verbose_name='Mediciones Antes')),
                ('measurements_after', models.JSONField(blank=True, default=dict, verbose_name='Mediciones Después')),
                ('adjustments_made', models.TextField(blank=True, verbose_name='Ajustes Realizados')),
                ('external_company', models.CharField(blank=True, max_length=200, verbose_name='Empresa Externa')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo')),
                ('certificate_number', models.CharField(blank=True, max_length=100, verbose_name='Número de Certificado')),
                ('certificate_file', models.FileField(blank=True, upload_to='calibration_certificates/', verbose_name='Archivo de Certificado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_records', to='equipment.equipment', verbose_name='Equipo')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Registro de Calibración',
                'verbose_name_plural': 'Registros de Calibración',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
