# Generated by Django 4.2.16 on 2025-07-29 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del módulo')),
                ('display_name', models.CharField(max_length=100, verbose_name='Nombre para mostrar')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('icon', models.CharField(default='fas fa-cog', max_length=50, verbose_name='Icono FontAwesome')),
                ('url_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre de URL')),
                ('category', models.CharField(choices=[('core', 'Módulos Básicos'), ('medical', 'Especialidades Médicas'), ('admin', 'Administración'), ('reports', 'Reportes y Analytics'), ('communication', 'Comunicación'), ('integration', 'Integraciones')], default='core', max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('requires_medical_license', models.BooleanField(default=False, verbose_name='Requiere licencia médica')),
                ('min_plan_required', models.CharField(choices=[('BASIC', 'Plan Básico'), ('MEDIUM', 'Plan Medio'), ('ADVANCED', 'Plan Avanzado')], default='BASIC', max_length=20)),
                ('order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('allowed_roles', models.JSONField(default=list, verbose_name='Roles permitidos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submodules', to='accounts.systemmodule')),
            ],
            options={
                'verbose_name': 'Módulo del Sistema',
                'verbose_name_plural': 'Módulos del Sistema',
                'ordering': ['category', 'order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('custom_settings', models.JSONField(blank=True, default=dict, verbose_name='Configuraciones personalizadas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='accounts.systemmodule')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Permiso de Módulo',
                'verbose_name_plural': 'Permisos de Módulos',
                'unique_together': {('organization', 'module')},
            },
        ),
    ]
