# Generated by Django 4.2.16 on 2025-08-03 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_systemmodule_modulepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('notification_type', models.CharField(choices=[('appointment', 'Cita Médica'), ('patient', 'Paciente'), ('system', 'Sistema'), ('reminder', 'Recordatorio'), ('alert', 'Alerta'), ('message', 'Mensaje')], default='system', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('is_dismissed', models.BooleanField(default=False, verbose_name='Descartada')),
                ('related_model', models.CharField(blank=True, max_length=100, verbose_name='Modelo relacionado')),
                ('related_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID relacionado')),
                ('action_url', models.URLField(blank=True, verbose_name='URL de acción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
