# Generated by Django 4.2.16 on 2025-07-30 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('report_type', models.CharField(choices=[('patients', 'Reporte de Pacientes'), ('appointments', 'Reporte de Citas'), ('financial', 'Reporte Financiero'), ('analytics', 'Análisis Avanzado'), ('medical', 'Reporte Médico'), ('custom', 'Reporte Personalizado')], max_length=20, verbose_name='Tipo de Reporte')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='Filtros')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Parámetros')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Fecha Desde')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Fecha Hasta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Archivo')),
                ('file_format', models.CharField(default='pdf', max_length=10, verbose_name='Formato')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='Programado')),
                ('schedule_frequency', models.CharField(blank=True, max_length=20, verbose_name='Frecuencia')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='Próxima Ejecución')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('report_type', models.CharField(choices=[('patients', 'Reporte de Pacientes'), ('appointments', 'Reporte de Citas'), ('financial', 'Reporte Financiero'), ('analytics', 'Análisis Avanzado'), ('medical', 'Reporte Médico'), ('custom', 'Reporte Personalizado')], max_length=20, verbose_name='Tipo')),
                ('template_config', models.JSONField(default=dict, verbose_name='Configuración')),
                ('default_filters', models.JSONField(blank=True, default=dict, verbose_name='Filtros por Defecto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_public', models.BooleanField(default=False, verbose_name='Público')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Plantilla de Reporte',
                'verbose_name_plural': 'Plantillas de Reportes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Puede Editar')),
                ('can_download', models.BooleanField(default=True, verbose_name='Puede Descargar')),
                ('shared_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Compartición')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira el')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='reports.report')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_reports', to=settings.AUTH_USER_MODEL, verbose_name='Compartido por')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Compartido con')),
            ],
            options={
                'verbose_name': 'Reporte Compartido',
                'verbose_name_plural': 'Reportes Compartidos',
                'unique_together': {('report', 'shared_with')},
            },
        ),
    ]
