# Generated by Django 4.2.16 on 2025-07-30 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Licencia')),
                ('education', models.TextField(blank=True, verbose_name='Educación')),
                ('certifications', models.TextField(blank=True, verbose_name='Certificaciones')),
                ('years_experience', models.PositiveIntegerField(default=0, verbose_name='Años de Experiencia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('accepts_new_patients', models.BooleanField(default=True, verbose_name='Acepta Nuevos Pacientes')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('photo', models.ImageField(blank=True, upload_to='doctors/', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('requires_referral', models.BooleanField(default=False, verbose_name='Requiere Referencia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('consultation_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de Consulta')),
                ('follow_up_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de Seguimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpecialtyConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(choices=[('initial', 'Consulta Inicial'), ('follow_up', 'Seguimiento'), ('emergency', 'Emergencia'), ('routine', 'Control de Rutina')], max_length=20, verbose_name='Tipo de Consulta')),
                ('date', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('chief_complaint', models.TextField(verbose_name='Motivo Principal de Consulta')),
                ('symptoms', models.TextField(blank=True, verbose_name='Síntomas')),
                ('physical_examination', models.TextField(blank=True, verbose_name='Examen Físico')),
                ('vital_signs', models.JSONField(blank=True, default=dict, verbose_name='Signos Vitales')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Diagnóstico')),
                ('treatment_plan', models.TextField(blank=True, verbose_name='Plan de Tratamiento')),
                ('medications', models.TextField(blank=True, verbose_name='Medicamentos')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Seguimiento')),
                ('follow_up_instructions', models.TextField(blank=True, verbose_name='Instrucciones de Seguimiento')),
                ('referral_needed', models.BooleanField(default=False, verbose_name='Necesita Referencia')),
                ('referral_reason', models.TextField(blank=True, verbose_name='Razón de Referencia')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completada')),
                ('notes', models.TextField(blank=True, verbose_name='Notas Adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.doctor', verbose_name='Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Paciente')),
                ('referral_specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='specialties.specialty', verbose_name='Especialidad de Referencia')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.specialty', verbose_name='Especialidad')),
            ],
            options={
                'verbose_name': 'Consulta de Especialidad',
                'verbose_name_plural': 'Consultas de Especialidades',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SpecialtyProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Procedimiento')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Duración (minutos)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('preparation_instructions', models.TextField(blank=True, verbose_name='Instrucciones de Preparación')),
                ('requires_anesthesia', models.BooleanField(default=False, verbose_name='Requiere Anestesia')),
                ('requires_fasting', models.BooleanField(default=False, verbose_name='Requiere Ayuno')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='specialties.specialty', verbose_name='Especialidad')),
            ],
            options={
                'verbose_name': 'Procedimiento de Especialidad',
                'verbose_name_plural': 'Procedimientos de Especialidades',
                'ordering': ['specialty', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpecialtyTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Tratamiento')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('status', models.CharField(choices=[('planned', 'Planificado'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('suspended', 'Suspendido'), ('cancelled', 'Cancelado')], default='planned', max_length=20, verbose_name='Estado')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('expected_end_date', models.DateField(blank=True, null=True, verbose_name='Fecha Esperada de Finalización')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Fecha Real de Finalización')),
                ('objectives', models.TextField(verbose_name='Objetivos del Tratamiento')),
                ('progress_notes', models.TextField(blank=True, verbose_name='Notas de Progreso')),
                ('medications', models.TextField(blank=True, verbose_name='Medicamentos')),
                ('outcomes', models.TextField(blank=True, verbose_name='Resultados')),
                ('complications', models.TextField(blank=True, verbose_name='Complicaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='specialties.specialtyconsultation', verbose_name='Consulta Origen')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.doctor', verbose_name='Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Paciente')),
                ('procedures', models.ManyToManyField(blank=True, to='specialties.specialtyprocedure', verbose_name='Procedimientos')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.specialty', verbose_name='Especialidad')),
            ],
            options={
                'verbose_name': 'Tratamiento de Especialidad',
                'verbose_name_plural': 'Tratamientos de Especialidades',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SpecialtyReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Razón de la Referencia')),
                ('urgency', models.CharField(choices=[('routine', 'Rutina'), ('urgent', 'Urgente'), ('emergency', 'Emergencia')], default='routine', max_length=20, verbose_name='Urgencia')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('scheduled', 'Programada'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('rejected', 'Rechazada')], default='pending', max_length=20, verbose_name='Estado')),
                ('relevant_history', models.TextField(blank=True, verbose_name='Historia Relevante')),
                ('current_medications', models.TextField(blank=True, verbose_name='Medicamentos Actuales')),
                ('test_results', models.TextField(blank=True, verbose_name='Resultados de Pruebas')),
                ('referral_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Referencia')),
                ('appointment_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cita')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('response', models.TextField(blank=True, verbose_name='Respuesta del Especialista')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recomendaciones')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('from_specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_from', to='specialties.specialty', verbose_name='Especialidad Origen')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Paciente')),
                ('receiving_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to='specialties.doctor', verbose_name='Doctor Receptor')),
                ('referring_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='specialties.doctor', verbose_name='Doctor Referente')),
                ('to_specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_to', to='specialties.specialty', verbose_name='Especialidad Destino')),
            ],
            options={
                'verbose_name': 'Referencia de Especialidad',
                'verbose_name_plural': 'Referencias de Especialidades',
                'ordering': ['-referral_date'],
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialties',
            field=models.ManyToManyField(to='specialties.specialty', verbose_name='Especialidades'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
