# Generated by Django 4.2.16 on 2025-07-29 05:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=20, unique=True, verbose_name='ID Paciente')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('mother_last_name', models.CharField(blank=True, max_length=50, verbose_name='Apellido materno')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'Prefiero no decir')], max_length=1, verbose_name='Género')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Formato: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=100, verbose_name='Estado')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Código postal')),
                ('blood_type', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('U', 'Desconocido')], default='U', max_length=3, verbose_name='Tipo de sangre')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura (cm)')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Soltero/a'), ('married', 'Casado/a'), ('divorced', 'Divorciado/a'), ('widowed', 'Viudo/a'), ('separated', 'Separado/a'), ('other', 'Otro')], max_length=20, verbose_name='Estado civil')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='Ocupación')),
                ('education_level', models.CharField(blank=True, max_length=100, verbose_name='Nivel educativo')),
                ('emergency_contact_name', models.CharField(max_length=100, verbose_name='Contacto de emergencia')),
                ('emergency_contact_relationship', models.CharField(max_length=50, verbose_name='Parentesco')),
                ('emergency_contact_phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Formato: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono de emergencia')),
                ('insurance_company', models.CharField(blank=True, max_length=100, verbose_name='Aseguradora')),
                ('insurance_policy', models.CharField(blank=True, max_length=50, verbose_name='Póliza')),
                ('insurance_group', models.CharField(blank=True, max_length=50, verbose_name='Grupo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('last_visit', models.DateTimeField(blank=True, null=True, verbose_name='Última visita')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='patients/photos/', verbose_name='Foto')),
                ('notes', models.TextField(blank=True, verbose_name='Notas generales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('systolic_pressure', models.IntegerField(blank=True, null=True, verbose_name='Presión sistólica')),
                ('diastolic_pressure', models.IntegerField(blank=True, null=True, verbose_name='Presión diastólica')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='Frecuencia cardíaca')),
                ('respiratory_rate', models.IntegerField(blank=True, null=True, verbose_name='Frecuencia respiratoria')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('oxygen_saturation', models.IntegerField(blank=True, null=True, verbose_name='Saturación de oxígeno (%)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura (cm)')),
                ('glucose_level', models.IntegerField(blank=True, null=True, verbose_name='Glucosa (mg/dL)')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='patients.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signos Vitales',
                'verbose_name_plural': 'Signos Vitales',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id', 'Identificación'), ('insurance', 'Seguro médico'), ('lab_result', 'Resultado de laboratorio'), ('imaging', 'Estudios de imagen'), ('prescription', 'Receta médica'), ('consent', 'Consentimiento informado'), ('other', 'Otros')], max_length=20, verbose_name='Tipo de documento')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('file', models.FileField(upload_to='patients/documents/', verbose_name='Archivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento del Paciente',
                'verbose_name_plural': 'Documentos del Paciente',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.TextField(blank=True, verbose_name='Alergias')),
                ('chronic_diseases', models.TextField(blank=True, verbose_name='Enfermedades crónicas')),
                ('previous_surgeries', models.TextField(blank=True, verbose_name='Cirugías previas')),
                ('current_medications', models.TextField(blank=True, verbose_name='Medicamentos actuales')),
                ('family_diseases', models.TextField(blank=True, verbose_name='Enfermedades familiares')),
                ('smoking_status', models.CharField(choices=[('never', 'Nunca ha fumado'), ('former', 'Ex fumador'), ('current', 'Fumador actual')], default='never', max_length=20, verbose_name='Estado de fumador')),
                ('alcohol_consumption', models.CharField(choices=[('none', 'No consume'), ('occasional', 'Ocasional'), ('moderate', 'Moderado'), ('heavy', 'Excesivo')], default='none', max_length=20, verbose_name='Consumo de alcohol')),
                ('exercise_frequency', models.CharField(choices=[('none', 'Sedentario'), ('low', 'Poco ejercicio'), ('moderate', 'Ejercicio moderado'), ('high', 'Ejercicio intenso')], default='none', max_length=20, verbose_name='Frecuencia de ejercicio')),
                ('menstrual_cycle_regular', models.BooleanField(blank=True, null=True, verbose_name='Ciclo menstrual regular')),
                ('pregnancies', models.IntegerField(blank=True, null=True, verbose_name='Embarazos')),
                ('births', models.IntegerField(blank=True, null=True, verbose_name='Partos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='patients.patient')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historia Médica',
                'verbose_name_plural': 'Historias Médicas',
            },
        ),
    ]
